### ISSUE TITLE
Exception from sub categoryTotals id 2XBq5Q5mq9A6GL8E8 Error: Match error: Expected string, got null

### ISSUE THREAD

**Issue by ashleyhsia0** [ashleyhsia0/trippay#14]
Kept getting this error for my pub/sub showing up in the console, as I have an argument passed into the pub and I checked to see if it is a string... but the component hasn't rendered yet and received the prop.

```
I20170325-03:05:49.517(-7)? Exception from sub categoryTotals id 2XBq5Q5mq9A6GL8E8 Error: Match error: Expected string, got null
I20170325-03:05:49.521(-7)?     at exports.check (packages/check/match.js:34:1)
I20170325-03:05:49.521(-7)?     at Subscription._handler (imports/api/trip-bills/server/publications.js:10:3)
I20170325-03:05:49.522(-7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20170325-03:05:49.522(-7)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20170325-03:05:49.523(-7)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20170325-03:05:49.523(-7)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20170325-03:05:49.526(-7)?     at packages/ddp-server/livedata_server.js:551:43
I20170325-03:05:49.533(-7)? Sanitized and reported to the client as: Match failed [400]
I20170325-03:05:49.534(-7)? 
```

**Comment by ashleyhsia0** [comment]
To solve this, I needed a conditional render, that once the prop is there, then to render the component:
```
{trip._id !== undefined &&
   <TripExpensesChart tripId={trip._id} bills={bills} />
}
```
